name: Electron Builder Action
author: kylsgl
description: GitHub Action for building and releasing Electron apps

inputs:
  args:
    description: Other arguments to pass to the `electron-builder` command, e.g. configuration overrides
    required: false
    default: ''
  build_script_name:
    description: Name of the optional NPM build script which is executed before `electron-builder`
    required: false
    default: build
  package_manager:
    description: Package manager to use
    required: false
  package_root:
    description: Directory where NPM/Yarn commands should be run
    required: false
    default: '.'
  github_token:
    description: GitHub authentication token
    required: true
  release:
    description: Whether the app should be released after a successful build
    required: false
    default: false
  linux_arch:
    description: Target arch for linux.
    required: false
    default: ''
  mac_arch:
    description: Target arch for mac.
    required: false
    default: ''
  mac_cert:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_cert_password:
    description: Password for decrypting `mac_cert`
    required: false
  windows_arch:
    description: Target arch for Windows
    required: false
    default: ''
  windows_cert:
    description: Base64-encoded code signing certificate for Windows
    required: false
  windows_cert_password:
    description: Password for decrypting `windows_cert`
    required: false

branding:
  icon: package
  color: blue

runs:
  using: node20
  main: dist/index.js
