name: Electron Builder Action
author: kylsgl
description: GitHub Action for building and releasing Electron apps

inputs:
  args:
    description: CLI args to pass to electron-builder
    required: false
    default: ''
  config_path:
    description: Path to electron-builder config file
    required: false
    default: ''
  script_before_build:
    description: Script to run before running electron-builder
    required: false
    default: ''
  package_manager:
    description: Package manager to use
    required: false
  package_root:
    description: Directory where commands should be run
    required: false
    default: '.'
  github_token:
    description: GitHub authentication token
    required: true
  publish:
    description: Publish on successful build
    required: false
    default: false
  linux_arch:
    description: Target arch for Linux.
    required: false
    default: ''
  mac_arch:
    description: Target arch for MacOS.
    required: false
    default: ''
  windows_arch:
    description: Target arch for Windows
    required: false
    default: ''

branding:
  icon: package
  color: blue

runs:
  using: node20
  main: dist/index.js
